services:
  prod-app:
    profiles: ["prod"]
    working_dir: /app
    build:
      args:
        - MINIFY_BACKEND_BUILD=${MINIFY_BACKEND_BUILD}
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "${EXTERNAL_SERVER_PORT}:3000"
    environment:
      - INTERNAL_SERVER_PORT=3000
    command: node server.js

  dev-app:
    profiles: ["dev"]
    working_dir: /project
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/project/app
      - /project/app/frontend/node_modules
      - /project/app/backend/node_modules
    ports:
      - "${EXTERNAL_SERVER_PORT}:3000"
    environment:
      - INTERNAL_SERVER_PORT=3000
    command: npm run dev
