# compose.prod.yaml
services:
  app:
    working_dir: /app
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
      args:
        MINIFY_BACKEND_BUILD: ${MINIFY_BACKEND_BUILD}
    restart: unless-stopped
    ports:
      - "${EXTERNAL_SERVER_PORT}:3000"
    command: node server.js
