# ---- Development stage ----
FROM node:22

WORKDIR /project

ARG NODE_ENV=development

ENV HUSKY=0
ENV NODE_ENV=$NODE_ENV
ENV FRONTEND_DIR=/project/app/frontend
ENV FRONTEND_INDEX_FILE=index.html

RUN apt-get update

# Just ensuring the file exists -> ENV_HUSKY is 0, thus husky is not initialized anyway.
COPY .husky/install.mts .husky/install.mts

COPY .npmrc ./
COPY package*.json ./
COPY app/shared/package*.json ./app/shared/
COPY app/backend/package*.json ./app/backend/
COPY app/frontend/package*.json ./app/frontend/

RUN npm ci