name: Run Quality

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-quality:
    name: run-quality
    runs-on: ubuntu-latest
    steps:
      - name: Setup node project
        uses: ./.github/actions/node-project-setup

      - name: Install dependencies
        run: ./.github/scripts/install-dependencies.sh

      - name: Run quality
        run: ./.github/scripts/quality.sh
