name: Run Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-test:
    name: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Setup node project
        uses: ./.github/actions/setup-node-project

      - name: Install dependencies
        run: ./.github/scripts/install-dependencies.sh

      - name: Run tests
        run: ./.github/scripts/test.sh
